### ISSUE TITLE
Please create a github release

### ISSUE THREAD

**Issue by martin-randall-tanium** [ash2k/bazel-tools#11]
Hi,

Please could you create a github release to allow pulling this repo with Bazel's `http_archive`? One benefit is that `http_archive` allows mirror URLs to be specified.

Thanks!

**Comment by ash2k** [comment]
Hi! Done https://github.com/ash2k/bazel-tools/releases/tag/v0.0.1

**Comment by martin-randall-tanium** [comment]
This works perfectly, thank you.

```
http_archive(
    name = "com_github_ash2k_bazel_tools",
    sha256 = "a7672b62441d56c84abad6d9dc6fac324859b1dc0e90b0652cbcbf5bb0d861e2",
    strip_prefix = "bazel-tools-0.0.1",
    url = "https://github.com/ash2k/bazel-tools/releases/download/v0.0.1/bazel-tools-0.0.1.tar.gz",
)
```
