### ISSUE TITLE
multirun with py_binary enhancement

### ISSUE THREAD

**Issue by dhoer** [ash2k/bazel-tools#14]
I was assuming that py_binary could be called by multirun.  Is there a way to detect the binary object type (andriod_binary, java_binary, cc_binary, sh_binary or py_binary) and execute based on that?

**Comment by ash2k** [comment]
multirun [looks at `files_to_run` in `DefaultInfo`](https://github.com/ash2k/bazel-tools/blob/f8b27b99cae951099385655e0bb0fc9cc1c7baa4/multirun/def.bzl#L49). If it's not there, then there is no way to run a target. If it's there but is not actually an OS executable, then it's probably wrong to have it specified as an executable.

I don't know if py_binary works or not. If it doesn't, then it would be good to find and fix the problem. What error are you getting?

**Comment by dhoer** [comment]
From the error, it seems to override the py_binary args with a blank array. 

I pass args in py_binary to a python script and when I run that target, it works.  But when I wrap it with multirun, the python script complains that required args are missing.

**Comment by ash2k** [comment]
I don't remember the details, but that sounds familiar. I think this might be the behavior I saw with `sh_binary`. That was the reason I built the `command()` rule. See the example https://github.com/ash2k/bazel-tools/tree/master/multirun and also check the source too (I'm not sure example is up to date).

**Comment by dhoer** [comment]
I'm not that familiar with go, but I think this would override the args array in the binary being processed: https://github.com/ash2k/bazel-tools/blob/master/multirun/multirun.go#L13

**Comment by ash2k** [comment]
Not really. It does not override anything. multirun calls the binary, defined by bazel rule. Bazel does not provide a way for a rule to define a binary and args for it, only the binary. If rule author needs to pass args to a binary, they usually wrap it in a shell script with arguments encoded. multirun just passes args to that wrapper script. How the wrapper deals with extra arguments is up to the rule authors.

**Comment by dhoer** [comment]
Thanks for the help on how binary bazel rules work.  I will go ahead and close this issue.
