### ISSUE TITLE
Goimports fails on go 1.18 upgrade

### ISSUE THREAD

**Issue by FastNav** [ash2k/bazel-tools#19]
Switching the Go SDK to 1.18 gives the following output during a goimports run.

```
4:1: expected statement, found 'package'
7:2: expected '}', found 'EOF'
4:1: expected statement, found 'package'
7:2: expected '}', found 'EOF'
4:1: expected statement, found 'package'
6:2: expected '}', found 'EOF'
```

Seems like an upgrade to the latest Go SDK might be necessary.

**Comment by ash2k** [comment]
Most likely we need a new goimports version that can parse new generics syntax or something like that. This can/should be fixed in this repo but you can also work this around by importing the (x/tools, IIRC) dependency before dependencies from this repo. Thanks for reporting.

**Comment by FastNav** [comment]
That solution doesn't seem to work for me unfortunately. There might be something deeper going on. I'll try applying the patch to this repo and see if that fixes it. I've been having some trouble so far for some reason.

**Comment by FastNav** [comment]
Ah it seems that we had some ill formed dummy files in the repo. The goimports tool stopped tolerating them after an upgrade to Go 1.18. Fixing those resolves the issue.

I'll close this ticket. Although upgrading to Go 1.18 probably would be a good idea :).
