### ISSUE TITLE
Support for Go version to v1.18

### ISSUE THREAD

**Issue by maniv1** [ash2k/bazel-tools#21]
bazel run //:golangcilint. works fine with  go_register_toolchains("1.17.7")

But with go_register_toolchains("1.18") we get error 
ERRO Running error: buildir: failed to load package goarch: could not load export data: cannot import "internal/goarch" (unknown iexport format version 2), export data is newer version - update tool 

I understand, 1.18 is not supported here yet. Hence the request.

**Comment by ash2k** [comment]
I'm not actively maintaining these rules, but will review a PR if someone opens it.

**Comment by maniv1** [comment]
I have raised a PR https://github.com/ash2k/bazel-tools/pull/22
The issue I was facing was with golangci-lint version. Bumping it to v1.46.2 fixed the issue

**Comment by ash2k** [comment]
Thank you!
