### ISSUE TITLE
multirun support for *_binary args

### ISSUE THREAD

**Issue by jfirebaugh** [ash2k/bazel-tools#23]
All Bazel binary rules have a common [`args` attribute](https://bazel.build/reference/be/common-definitions#binary.args). However if you set up a `*_binary` target with `args` and then name it in a multirun target's `commands`, multirun doesn't run it with those args. You can work around this with multirun's `command`, but it would be better if you didn't need to duplicate the args in two places. Perhaps multirun could use an [aspect](https://bazel.build/rules/aspects) to obtain the args from any `*_binary` dependencies?

(This is effectively a generalization of https://github.com/ash2k/bazel-tools/issues/14, which asked about `py_binary` specifically. The discussion there glosses over the built in `args` attribute though.)

**Comment by ash2k** [comment]
Thanks for the issue. I don't think it's necessarily a problem - a binary may be run with different arguments, even in the same build/`run`. So concatenating arguments from the `_binary`, `command`, etc may not be desirable. I think it's a deficiency in the bazel's `_binary` "API" - it combines two things in one. `args` shouldn't be a common attribute for the above reasons - you may want to run your binary with different args. How do I do that if using vanilla bazel? Only via `genrule` of something like it. Ok, cool, why have `args` in the first place then? Feels unnecessary. I think instead bazel should have provided two rules/macros - one to define the binary and another one to define an execution of that binary. And that's what I did with `command`+`_binary`.

I also think it's not worth complicating the library with aspects as the use case is already solvable with existing rules/macros.
